use ConvICine

INSERT INTO ESTADO VALUES ('Activo');
INSERT INTO ESTADO VALUES ('Inactivo');
INSERT INTO ESTADO VALUES ('Fuera de Servicio momentaneamente');
INSERT INTO ESTADO VALUES ('libre');
INSERT INTO ESTADO VALUES ('Realizado');
INSERT INTO ESTADO VALUES ('Cancelada');

select * from ESTADO

--Insert en la tabla Sala

INSERT INTO SALA VALUES ('SALA 1',200,4);

INSERT INTO SALA VALUES ('SALA 2',200,4);

INSERT INTO SALA VALUES ('SALA VIP',100,4);

select * from SALA



--Insert en la tabla Pelicula

INSERT INTO PELICULA VALUES ('Transformers','01:30:00','ACCION','APTO PARA TODOS','3D',1);
INSERT INTO PELICULA VALUES ('Avatar 2','02:30:00','ACCION','Clasificacion R','2D',1);

select * from PELICULA


---------------------------------------------------------------
------------------------Asientos-------------------------------


-- SALA 1
INSERT INTO ASIENTO VALUES (1,1,1);
INSERT INTO ASIENTO VALUES (2,1,1);
INSERT INTO ASIENTO VALUES (3,1,1);
INSERT INTO ASIENTO VALUES (4,1,1);
INSERT INTO ASIENTO VALUES (5,1,1);
INSERT INTO ASIENTO VALUES (6,1,1);
INSERT INTO ASIENTO VALUES (7,1,1);
INSERT INTO ASIENTO VALUES (8,1,1);
INSERT INTO ASIENTO VALUES (9,1,1);
INSERT INTO ASIENTO VALUES (10,1,1);
INSERT INTO ASIENTO VALUES (11,1,1);
INSERT INTO ASIENTO VALUES (12,1,1);
INSERT INTO ASIENTO VALUES (13,1,1);
INSERT INTO ASIENTO VALUES (14,1,1);
INSERT INTO ASIENTO VALUES (15,1,1);
INSERT INTO ASIENTO VALUES (16,1,1);
INSERT INTO ASIENTO VALUES (17,1,1);
INSERT INTO ASIENTO VALUES (18,1,1);
INSERT INTO ASIENTO VALUES (19,1,1);
INSERT INTO ASIENTO VALUES (20,1,1);
INSERT INTO ASIENTO VALUES (21,1,1);
INSERT INTO ASIENTO VALUES (22,1,1);
INSERT INTO ASIENTO VALUES (23,1,1);
INSERT INTO ASIENTO VALUES (24,1,1);
INSERT INTO ASIENTO VALUES (25,1,1);

--La sala puede tener hasta 200 asientos pero aqui solo se agregaron 25 
--este tipo de caso para asignar un asiento es mejor que solo darle un numero a un asiento
--debido a que podemos saber si el asiento ya esta ocupado o si esta activo o inavilitado 'X' razon

select * from ASIENTO

  --SALA 2

INSERT INTO ASIENTO VALUES (1,2,1);
INSERT INTO ASIENTO VALUES (2,2,1);
INSERT INTO ASIENTO VALUES (3,2,1);
INSERT INTO ASIENTO VALUES (4,2,1);
INSERT INTO ASIENTO VALUES (5,2,1);
INSERT INTO ASIENTO VALUES (6,2,1);
INSERT INTO ASIENTO VALUES (7,2,1);
INSERT INTO ASIENTO VALUES (8,2,1);
INSERT INTO ASIENTO VALUES (9,2,1);
INSERT INTO ASIENTO VALUES (10,2,1);
INSERT INTO ASIENTO VALUES (11,2,1);
INSERT INTO ASIENTO VALUES (12,2,1);
INSERT INTO ASIENTO VALUES (13,2,1);
INSERT INTO ASIENTO VALUES (14,2,1);
INSERT INTO ASIENTO VALUES (15,2,1);
INSERT INTO ASIENTO VALUES (16,2,1);
INSERT INTO ASIENTO VALUES (17,2,1);
INSERT INTO ASIENTO VALUES (18,2,1);
INSERT INTO ASIENTO VALUES (19,2,1);
INSERT INTO ASIENTO VALUES (20,2,1);
INSERT INTO ASIENTO VALUES (21,2,1);
INSERT INTO ASIENTO VALUES (22,2,1);
INSERT INTO ASIENTO VALUES (23,2,1);
INSERT INTO ASIENTO VALUES (24,2,1);
INSERT INTO ASIENTO VALUES (25,2,1);

-- SALA VIP
INSERT INTO ASIENTO VALUES (1,3,1);
INSERT INTO ASIENTO VALUES (2,3,1);
INSERT INTO ASIENTO VALUES (3,3,1);
INSERT INTO ASIENTO VALUES (4,3,1);
INSERT INTO ASIENTO VALUES (5,3,1);
INSERT INTO ASIENTO VALUES (6,3,1);
INSERT INTO ASIENTO VALUES (7,3,1);
INSERT INTO ASIENTO VALUES (8,3,1);
INSERT INTO ASIENTO VALUES (9,3,1);
INSERT INTO ASIENTO VALUES (10,3,1);
INSERT INTO ASIENTO VALUES (11,3,1);
INSERT INTO ASIENTO VALUES (12,3,1);
INSERT INTO ASIENTO VALUES (13,3,1);
INSERT INTO ASIENTO VALUES (14,3,1);
INSERT INTO ASIENTO VALUES (15,3,1);
INSERT INTO ASIENTO VALUES (16,3,1);
INSERT INTO ASIENTO VALUES (17,3,1);
INSERT INTO ASIENTO VALUES (18,3,1);
INSERT INTO ASIENTO VALUES (19,3,1);
INSERT INTO ASIENTO VALUES (20,3,1);
INSERT INTO ASIENTO VALUES (21,3,1);
INSERT INTO ASIENTO VALUES (22,3,1);
INSERT INTO ASIENTO VALUES (23,3,1);
INSERT INTO ASIENTO VALUES (24,3,1);
INSERT INTO ASIENTO VALUES (25,3,1);


-- Cliente

INSERT INTO CLIENTE VALUES ('juan','morales','22225454');

--Cartelera
INSERT INTO CARTELERA VALUES (1,1,'18:00:00','19:30:00',CURRENT_TIMESTAMP,1);

--Empleado
INSERT INTO EMPLEADO VALUES ('JOSE','HERNANDEZ',CURRENT_TIMESTAMP,1);

--Tipos de tickert

INSERT INTO TICKET VALUES ('ENTRADA GENERAL','ENTRADA PARA LAS PERSONAS MAYORES DE 18 AÑOS',150,1);

INSERT INTO TICKET VALUES ('ENTRADA NIÑOS','ENTRADA PARA LOS NINOS',100,1);

INSERT INTO TICKET VALUES('ENTRADA TERCERA EDAD','ENTRADA PARA PERSONAS MAYORES A 60 AÑOS',100,1);

INSERT INTO TICKET VALUES('ENTRADA ESTUDIANTES','ENTRADA PARA ESTUDIANTES QUE PRESENTAN CARNET',130,1);

--promocion

INSERT INTO PROMOCION VALUES ('PROMOCION 2X1',1.0,1,1);

INSERT INTO PROMOCION VALUES ('DESCUENTO 30%',0.3,0,1);

INSERT INTO PROMOCION VALUES ('DESCUENTO 50%',0.5,0,1);

select * from PROMOCION


INSERT INTO PROGRPROMOCION VALUES (CURRENT_TIMESTAMP,'DESCUENTO 30%',2);

INSERT INTO PROGRPROMOCION VALUES ('2022-12-24','DESCUENTO 50%',1);

INSERT INTO PROGRPROMOCION VALUES (CURRENT_TIMESTAMP,'PROMOCION 3x2',1);



select * from PROGRPROMOCION



select * from ESTADO

