create database ConvICine

use ConvICine

create table ESTADO(

 IDESTADO INT IDENTITY(1,1) not null,
 DESCRIPCION VARCHAR(50) not null,
 CONSTRAINT PK_ESTADO PRIMARY KEY (IDESTADO)
)
go

create table SALA(

 IDSALA INT  IDENTITY(1,1) not null,
 DESCRIPCION VARCHAR(50) not null,
 ASIENTOS INT not null,
 IDESTADO INT not null,
 CONSTRAINT PK_SALA PRIMARY KEY (IDSALA),
 CONSTRAINT FK_SALA_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

create table CLIENTE(

IDCLIENTE INT NOT NULL IDENTITY (1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI CHAR(8) NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE)
)
go


create table PELICULA(

 IDPELICULA INT IDENTITY(1,1) not null,
 TITULO VARCHAR(50) not null,
 DURACION TIME not null,
 GENERO VARCHAR(50) not null,
 CLASIFICACION VARCHAR(50) not null,
 FORMATO VARCHAR(40) not null,
 IDESTADO INT not null,
 CONSTRAINT PK_PELICULA PRIMARY KEY (IDPELICULA),
 CONSTRAINT FK_PELICULA_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

CREATE TABLE ASIENTO(

 IDASIENTO INT IDENTITY (1,1) not null,
 NROASIENTO INT not null,
 IDSALA INT not null,
 CONSTRAINT PK_ASIENTO PRIMARY KEY (IDASIENTO),
 CONSTRAINT FK_ASIENTO_SALA FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA),
 
)
go

alter table ASIENTO add IDESTADO INT not null

alter table ASIENTO add CONSTRAINT FK_ASIENTO_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)



CREATE TABLE CARTELERA(

 IDCARTELERA INT IDENTITY (1,1) not null,
 IDPELICULA INT not null,
 IDSALA INT not null,
 HORAINICIO TIME not null,
 HORAFIN TIME not null,
 FECHA DATE not null,
 IDESTADO INT not null,
 CONSTRAINT PK_CARTELERA PRIMARY KEY (IDCARTELERA),
 CONSTRAINT FK_CARTELERA_PELICULA FOREIGN KEY (IDPELICULA) REFERENCES PELICULA(IDPELICULA),
 CONSTRAINT FK_CARTELERA_SALA FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA),
 CONSTRAINT FK_CARTELERA_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

CREATE TABLE REGISTROASIENTO(

 IDRASIENTO INT not null IDENTITY(1,1),
 IDCARTELERA INT not null,
 NROASIENTO INT not null,
 CONSTRAINT PK_RASIENTO PRIMARY KEY (IDRASIENTO),
 CONSTRAINT FK_RASIENTO_CARTELERA FOREIGN KEY (IDCARTELERA) REFERENCES CARTELERA(IDCARTELERA)
)
go

CREATE TABLE ASIENTOCLIENTE(

 IDACLIENTE INT IDENTITY (1,1) not null,
 IDRASIENTO INT not null,
 IDCLIENTE INT not null,
 CONSTRAINT PK_ACLIENTE PRIMARY KEY (IDACLIENTE),
 CONSTRAINT FK_ACLIENTE_RCLIENTE FOREIGN KEY (IDRASIENTO) REFERENCES REGISTROASIENTO(IDRASIENTO),
 CONSTRAINT FK_ACLIENTE_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
)
go

CREATE TABLE EMPLEADO(

 IDEMPLEADO INT IDENTITY (1,1)not null,
 NOMBRE VARCHAR(50) not null,
 APELLIDO VARCHAR(50) not null,
 FECHACONTRAT DATE not null,
 IDESTADO INT not null,
 CONSTRAINT PK_EMPLEADO PRIMARY KEY (IDEMPLEADO),
 CONSTRAINT FK_EMPLEADO_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

CREATE TABLE TICKET(

 IDTICKET INT IDENTITY (1,1) not null,
 TIPO VARCHAR(80) not null,
 DESCRIPCION VARCHAR(200) not null,
 PRECIO DECIMAL(10,2) not null,
 IDESTADO INT not null,
 CONSTRAINT PK_TICKET PRIMARY KEY (IDTICKET),
 CONSTRAINT FK_TICKET_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

CREATE TABLE VENTA(

 IDVENTA INT IDENTITY (1,1) not null,
 IDCLIENTE INT not null,
 IDCARTELERA INT not null,
 IDEMPLEADO INT not null,
 FECHA DATE not null,
 ASIENTOS VARCHAR(20) not null,
 TPAGO VARCHAR(50) not null,
 PROMOCION VARCHAR(80) not null,
 DESCUENTO DECIMAL(10,2) not null,
 IDESTADO INT not null,
 CONSTRAINT PK_VENTA PRIMARY KEY (IDVENTA),
 CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
 CONSTRAINT FK_VENTA_CARTELERA FOREIGN KEY (IDCARTELERA) REFERENCES CARTELERA(IDCARTELERA),
 CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO),
 CONSTRAINT FK_VENTA_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)
go

CREATE TABLE DETALLEVENTA(

 IDDVENTA INT IDENTITY(1,1) not null,
 IDVENTA INT not null,
 DESCRIPCION VARCHAR(100) not null,
 CANTIDAD INT not null,
 PRECIO DECIMAL(10,2) not null,
 CONSTRAINT PK_DVENTA PRIMARY KEY (IDDVENTA),
 CONSTRAINT FK_DVENTA_VENTA FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA)
)
go

CREATE TABLE PROMOCION(

 IDPROMOCION INT IDENTITY(1,1) not null,
 NOMBRE VARCHAR(80) not null,
 DESCUENTO DECIMAL (10,2) not null,
 BASETICKET BIT not null,
 IDESTADO INT not null,
 CONSTRAINT PK_PROMOCION PRIMARY KEY (IDPROMOCION),
 CONSTRAINT FK_PROMOCION_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO),
)
go

create table PROGRPROMOCION(

IDPPROMOCION INT IDENTITY(1,1) not null,
FECHA DATE not null,
PROMOCION VARCHAR(80) not null,
IDESTADO INT not null,
CONSTRAINT PK_PPROMOCION PRIMARY KEY (IDPPROMOCION),
CONSTRAINT FK_PPROMOCION_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
)