use ConvICine

CREATE TRIGGER T_VENTAASIENTO 
  ON REGISTROASIENTO
  AFTER INSERT 
  as
BEGIN
 INSERT INTO ASIENTOCLIENTE select i.IDRASIENTO,v.IDCLIENTE from inserted i inner 
 join VENTA v on v.IDVENTA=i.IDRASIENTO;

 UPDATE ASIENTO SET IDESTADO=3  FROM inserted i where ASIENTO.IDASIENTO =i.NROASIENTO;
 
END;